name: Update Submodules

on:
  schedule:
    - cron: '0 11 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true # Checkout submodules

      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Automated submodule update"
          git push origin main
